root: true
extends:
  - '@willin'
  - plugin:@typescript-eslint/recommended-requiring-type-checking
parserOptions:
  project: ./tsconfig.json
rules:
  '@typescript-eslint/explicit-function-return-type': 0
