root: true
extends:
  - '@willin'
  - plugin:@typescript-eslint/recommended-requiring-type-checking
plugins:
  - import
parserOptions:
  project: ./tsconfig.json
  tsconfigRootDir: ./
settings:
  import/resolver:
    typescript: {}
rules:
  '@typescript-eslint/explicit-function-return-type': 0
